### ISSUE TITLE
Unit openvpn.service failed to load: No such file or directory.

### ISSUE THREAD

**Issue by wedojava** [viljoviitanen/setup-simple-openvpn#10]
my vps is CentOS 7.1 System, when i run `sudo sh normal-setup.sh`

at the end ,there is something wrong,the log is :

```
The server 'openvpn-udp-1194' uses port 1194 protocol udp.
Make sure they are open in an external firewall if there is one.
/bin/yum
服务 openvpn 信息读取出错：没有那个文件或目录
Redirecting to /bin/systemctl start  openvpn.service
Failed to issue method call: Unit openvpn.service failed to load: No such file or directory.
```

PLS, Help! Thanks!!

**Comment by viljoviitanen** [comment]
Use centos 6.

Ite seems centos 7 does not work with this script.

**Comment by niugeshenhua** [comment]
@viljoviitanen  Hey, man, I am use centos7 cannt use 6, Do you have a good idea rather than it?

**Comment by viljoviitanen** [comment]
Well, if you need to have openvpn on centos 7, you cannot use my script to do it. I'm not really interested in adapting the script to centos 7. Install and configure openvpn manually, see https://www.google.com/#q=openvpn%20centos%207 for instructions.
