### ISSUE TITLE
DNS problem using script on openvz centos6

### ISSUE THREAD

**Issue by a1000ydStare** [viljoviitanen/setup-simple-openvpn#11]
Thanks for the script.  Im able to connect but, can't get to the internet.  Not sure if it's a DNS problem because if I enter a verified ip in my address bar I still can't get out.  Any ideas what to check?  Thanks

**Comment by viljoviitanen** [comment]
I'm sorry, absolutely no tech support here.

**Comment by a1000ydStare** [comment]
Understood.  I thought it was worth mentioning since this was a fresh vps with centos 6 and the script completely successfully, just not working right.  Np thanks anyways.

**Comment by viljoviitanen** [comment]
Try on some other cloud provider, check possible cloud provider firewall settings, problems with your isp/own connection dropping openvpn packets for some reason.. etc. Or the image your cloud provider uses just isn't compatible, they could have made some small change on some critical file... A lot of things could be wrong.

**Comment by a1000ydStare** [comment]
Will do, ty!
